use master 
go
alter database DB_TRANSLATE set single_user with rollback immediate

drop database DB_TRANSLATE
go
CREATE DATABASE DB_TRANSLATE
GO
--ALTER DATABASE DB_TRANSLATE
--COLLATE Latin1_General_100_CI_AS_SC_UTF8;
--GO
USE DB_TRANSLATE
GO

---------------CREATE TABLE---------------
CREATE TABLE ACCOUNT
(
	UID INT NOT NULL IDENTITY,
	USERNAME NVARCHAR(50),
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASS VARCHAR(61) NOT NULL,
	CONSTRAINT PK_ACCOUNT PRIMARY KEY(UID)
)
GO

CREATE TABLE HISTORY
(
	WORDID INT NOT NULL IDENTITY,
	ORIGINALWORD NVARCHAR(MAX),
	TRANSLATEDWORD NVARCHAR(MAX),
	FROMLANGUAGE VARCHAR(20),
	TOLANGUAGE VARCHAR(20),
	TIMESAVE DATETIME,
	UID INT,
	CONSTRAINT PK_HISTORY PRIMARY KEY(WORDID)
)
GO

CREATE TABLE FAVORITE
(
	WORDID INT NOT NULL IDENTITY,
	ORIGINALWORD NVARCHAR(MAX),
	TRANSLATEDWORD NVARCHAR(MAX),
	FROMLANGUAGE VARCHAR(20),
	TOLANGUAGE VARCHAR(20),
	TIMESAVE DATETIME,
	UID INT,
	CONSTRAINT PK_FAVORITE PRIMARY KEY(WORDID)
)
GO

---------------FOREIGN KEY----------
ALTER TABLE FAVORITE ADD CONSTRAINT FK_ACCOUNT_FAVORITE FOREIGN KEY (UID) REFERENCES ACCOUNT(UID)
GO
ALTER TABLE HISTORY ADD CONSTRAINT FK_ACCOUNT_HISTORY FOREIGN KEY (UID) REFERENCES ACCOUNT(UID)
GO

---------Stored Procedure----------
CREATE PROCEDURE AddAccount
    @Username NVARCHAR(50),
    @Email VARCHAR(50),
    @Password VARCHAR(61)
AS
BEGIN
    INSERT INTO ACCOUNT (USERNAME, EMAIL, PASS)
    VALUES (@Username, @Email, @Password);
END
GO

--------------INSERT------------
SET DATEFORMAT DMY

EXEC AddAccount @Username = 'thanhtruc', @Email = 'thanhtruc@gmail.com', @Password = 'truc0307';
EXEC AddAccount @Username = 'ductruong', @Email = 'ductruong@gmail.com', @Password = 'truong0807';
EXEC AddAccount @Username = 'baongan', @Email = 'baongan@gmail.com', @Password = 'ngan0402';